### ISSUE TITLE
Volume Control and etc...

### ISSUE THREAD

**Issue by Sepehr13** [DavidLazic/audio-visualizer#1]
Hi
thanks for this great plugin, i've been looking for it like forever!
but there is one problem or maybe multiple problems!
one of them id how can i control the volume when user clicks on a button?
i tried gainNode but when the gainNode is set, it's set forever and i can't change it while audio is playing.
another problem is how can i change the song when a button is pressed ?

**Comment by LazicDavid** [comment]
Hi Sepehr,

I've been receiving a lot of requests regarding visualizer lately. I'd like to notice here that this "project" is just a demo, an example of how audio files could be visualized, it's not a fully working example, and the functionality that you've mentioned is non existent. This was supposed to be only an inspiration how audio data can be **visualized**.

If it's a comfort, I'm currently working on making fully customizable React component (visualizer), where I could add these sort of functionalities, e.g. full player with list and controls. I'll publish it on npm as soon as I'm done making it.
