### ISSUE TITLE
Cannot read property 'setAnalyser' of undefined

### ISSUE THREAD

**Issue by robsok** [DavidLazic/audio-visualizer#2]
Hi, I had an issue, but solved it since then ... but I was not able to 'remove' this comment. So therefore, the only thing that is left for me to do is to thank you for your beautifully designed visual element!

**Comment by DavidLazic** [comment]
Hi Rob, 

Yeah, I had read your original comment, was going to check it out now, but I'm glad you've solved it already :)

Let me just give you a notice that this visualizer hasn't been tested properly, nor it is (in my opinion) production ready, it was written in a moment of inspiration but later there was no time for bug fixes and code updates. If it suits your needs then use it as you want =)

Cheers!
